config/urls.py
import os
from django.contrib import admin
from django.urls import path,include
#para los media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.login.urls')),
    path('crm/',include('core.crm.urls')),
    path('user/',include('core.user.urls')),
    path('encuesta/',include('core.encuesta.urls')),
    path('prediction/',include('core.predictions.urls')),
]

#para la url de los media en desarrollo
if not 'WEBSITE_HOSTNAME' in os.environ:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/crm/urls.py
from django.urls import path
from core.crm.views.categoria.views import *
from core.crm.views.dashboard.views import *
from core.crm.views.empresa.views import EmpresaCreateView, EmpresaDeleteView, EmpresaListView, EmpresaUpdateView
from core.crm.views.presupuesto.views import PresupuestoCreateView, PresupuestoDeleteView, PresupuestoListView, PresupuestoUpdateView
from core.crm.views.producto.views import *
from core.crm.views.sede.views import SedeCreateView, SedeDeleteView, SedeListView, SedeUpdateView
from core.crm.views.servicio.views import ServicioCreateView, ServicioDeleteView, ServicioListView, ServicioUpdateView
from core.crm.views.trabajador.views import TrabajadorCreateView, TrabajadorDeleteView, TrabajadorListView, TrabajadorUpdateView

app_name = 'crm'

urlpatterns = [
    #Categoria
    path('categoria/list/', CategoriaListView.as_view(), name='categoria_list'),
    path('categoria/add/', CategoriaCreateView.as_view(), name='categoria_create'),
    path('categoria/update/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categoria/delete/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_delete'),

    # producto
    path('producto/list/', ProductoListView.as_view(), name='producto_list'),
    path('producto/add/', ProductoCreateView.as_view(), name='producto_create'),
    path('producto/update/<int:pk>/', ProductoUpdateView.as_view(), name='producto_update'),
    path('producto/delete/<int:pk>/', ProductoDeleteView.as_view(), name='producto_delete'),

    # empresa
    path('empresa/list/', EmpresaListView.as_view(), name='empresa_list'),
    path('empresa/add/', EmpresaCreateView.as_view(), name='empresa_create'),
    path('empresa/update/<int:pk>/', EmpresaUpdateView.as_view(), name='empresa_update'),
    path('empresa/delete/<int:pk>/', EmpresaDeleteView.as_view(), name='empresa_delete'),

    # sede
    path('sede/list/', SedeListView.as_view(), name='sede_list'),
    path('sede/add/', SedeCreateView.as_view(), name='sede_create'),
    path('sede/update/<int:pk>/', SedeUpdateView.as_view(), name='sede_update'),
    path('sede/delete/<int:pk>/', SedeDeleteView.as_view(), name='sede_delete'),

    # trabajador
    path('trabajador/list/', TrabajadorListView.as_view(), name='trabajador_list'),
    path('trabajador/add/', TrabajadorCreateView.as_view(), name='trabajador_create'),
    path('trabajador/update/<int:pk>/', TrabajadorUpdateView.as_view(), name='trabajador_update'),
    path('trabajador/delete/<int:pk>/', TrabajadorDeleteView.as_view(), name='trabajador_delete'),

    #servicio
    path('servicio/list/', ServicioListView.as_view(), name='servicio_list'),
    path('servicio/add/', ServicioCreateView.as_view(), name='servicio_create'),
    path('servicio/update/<int:pk>/', ServicioUpdateView.as_view(), name='servicio_update'),
    path('servicio/delete/<int:pk>/', ServicioDeleteView.as_view(), name='servicio_delete'),
    
    #presupuesto
    path('presupuesto/list/', PresupuestoListView.as_view(), name='presupuesto_list'),
    path('presupuesto/add/', PresupuestoCreateView.as_view(), name='presupuesto_create'),
    path('presupuesto/update/<int:pk>/', PresupuestoUpdateView.as_view(), name='presupuesto_update'),
    path('presupuesto/delete/<int:pk>/', PresupuestoDeleteView.as_view(), name='presupuesto_delete'),

    #Home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

]        

core/predictions/urls.py
from django.urls import path
from core.predictions.views import (
    ChartByQuantityView,
    ChartByValueView,
    PredictionView,
    PredictionViewThirty,
    PredictionPublicationFacebookView,
    PredictionLandingPageView,
)

app_name = "predictions"

urlpatterns = [
    path("by-quantity/", ChartByQuantityView.as_view(), name="prediction_quantity"),
    path("by-value/", ChartByValueView.as_view(), name="prediction_value"),

    # predictions
    path("future/", PredictionView.as_view(), name="predictions_view"),
    path("future/30/", PredictionViewThirty.as_view(), name="predictions_view_thirty"),
    path("publications/facebook/", PredictionPublicationFacebookView.as_view(), name="prediction_publication_facebook"),
    path("landing/", PredictionLandingPageView.as_view(), name="predictions_landing"),
]

core/user/urls.py
from django.urls import path
from core.user.views import *


app_name = 'user'

urlpatterns = [
    #Usuario
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    ]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    {% csrf_token %}
    <body class="hold-transition sidebar-mini layout-fixed sidebar-collapse">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block js %}

    {% endblock %}
    <script>


      {% if messages %}
    var html = '<p>';
        {% for message in messages %}
        html += '{{ message }}<br>';
        {% endfor %}
        html += '</p>';
        Swal.fire({
            title: 'Error!',
            html: html,
            icon: 'error'
            });
        {% endif %}


    if (window && window.localStorage.getItem('sidebar') !== 'active') {
        // if it active show it as active
        $(".sidebar-mini").removeClass("sidebar-collapse");
    }

    $("#btn-collapse").click(function() {
        $(".sidebar-mini").toggleClass("sidebar-collapse");
         var updated = '';
         if (window.localStorage.getItem('sidebar') === 'active') {
             updated = 'not_active';
         } else {
             updated = 'active';
         }
         window.localStorage.setItem('sidebar', updated);
    }); 

    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" id="btn-collapse" data-widget="pushmenu-old" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/crm/dashboard/" class="nav-link">Inicio</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-user"></i> {{request.user.username|title}}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-gray elevation-4">
    <a href="{% url "crm:dashboard" %}" class="brand-link">
        <img src="{% static 'media/img/logo.png' %}"
             alt="Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Proyecto</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{user.get_image}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block"> {% if user.is_authenticated %}
                  {{request.user.username|title}}
                  {% else %}
                  Sin iniciar sesión
                  {% endif %}
                  </a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
                <li class="nav-item">
                    <a href="{% url 'crm:categoria_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-truck-loading"></i>
                        <p>
                            Categorías
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "crm:producto_list" %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Productos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "crm:servicio_list" %}" class="nav-link">
                        <i class="nav-icon fas fa-truck-loading"></i>
                        <p>
                            Servicios
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "crm:presupuesto_list" %}" class="nav-link">
                        <i class="nav-icon fas fa-dollar-sign"></i>
                        <p>
                            Presupuestos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "crm:trabajador_list" %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Trabajadores
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "user:user_list" %}" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Usuarios
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "crm:empresa_list" %}" class="nav-link">
                        <i class="nav-icon fas fa-building"></i>
                        <p>
                            Empresas
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "crm:sede_list" %}" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Sedes
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "predictions:prediction_value" %}" class="nav-link">
                        <i class="nav-icon fas fa-history"></i>
                        <p>
                            Histórico Valor
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "predictions:prediction_quantity" %}" class="nav-link">
                        <i class="nav-icon fas fa-camera"></i>
                        <p>
                            Histórico Cantidad
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "predictions:predictions_view" %}" class="nav-link">
                        <i class="nav-icon fas fa-magic"></i>
                        <p>
                            Predicciones Prophet
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "predictions:predictions_view_thirty" %}" class="nav-link">
                        <i class="nav-icon fas fa-list"></i>
                        <p>
                            Predicciones Tensorflow
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "predictions:prediction_publication_facebook" %}" class="nav-link">
                        <i class="nav-icon fas fa-bell"></i>
                        <p>
                            Publicaciones Facebook
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "predictions:predictions_landing" %}" class="nav-link">
                        <i class="nav-icon fas fa-star"></i>
                        <p>
                            Predicciones Landing
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>